server {
	listen 8091;
	listen [::]:8091;
	
	server_name 160.187.229.99;

	root /var/www/devops-practice-de002-khanhan007/src;
	index index.html;

	access_log /var/log/nginx/khanhan-lab.access.log;
	error_log /var/log/nginx/khanhan-lab.error.log;

	location / {
		try_files $uri $uri/ =404;
	}
}
